"""empty message

Revision ID: 346dba43d24b
Revises: ed08603b9c2e
Create Date: 2024-07-01 20:55:31.896897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346dba43d24b'
down_revision = 'ed08603b9c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)

    # ### end Alembic commands ###
